default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  port: 3306
  host: <%= ENV['DB_HOST'] %>
  username: <%= Rails.application.credentials[:database][:username] %>
  password: <%= Rails.application.credentials[:database][:password] %>

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test
production:
  <<: *default
  database: blog_production
